version: "3.9"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:

    transmission:
        image: lscr.io/linuxserver/transmission:latest
        container_name: transmission
        environment:
            - USER=$user #optional
            - PASS=$pass #optional
            - PUID=$puid
            - PGID=$guid
            - TZ=$tzone
#           - TRANSMISSION_WEB_HOME=/transmission-web-control/ #alternative gui /transmission-web-control/ or /kettu/ or /combustion-release/
        volumes:
            - ${app_data}/transmission:/config
            - ${media}/download:/downloads
            - ${media}/download/watch:/watch
        ports:
            - 9091:9091
            - 51413:51413
            - 51413:51413/udp
        restart: always
        networks:
            - private

    kms:
        image: teddysun/kms:latest
        container_name: kms
        environment:
            - PUID=$puid
            - PGID=$guid
            - TZ=$tzone
        ports:
            - 1688:1688
        restart: always
        networks:
            - private

    watchtower:
        image: containrrr/watchtower:latest
        container_name: watchtower
        environment:
            - WATCHTOWER_NOTIFICATIONS=email
            - WATCHTOWER_NOTIFICATION_EMAIL_FROM=$yanbox
            - WATCHTOWER_NOTIFICATION_EMAIL_TO=$mailbox
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER=smtp.yandex.ru
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PORT=587
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_USER=$yanbox
            - WATCHTOWER_NOTIFICATION_EMAIL_SERVER_PASSWORD=$pass
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command:
#            --interval 86400
            --cleanup
            --schedule "0 0 0 * * *"
        restart: always
        networks:
            - private

networks:
    private:
        external: true
#            name: private
